name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: run
      run: npx zx bump.js
