name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install
      run: npm i -g zx
    - name: run dependabot script
      run: ls && ./bump.js
